# Generated by Django 6.0.2 on 2026-03-05 16:18

import crypto_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': "Journal d'activité", 'verbose_name_plural': "Journaux d'activité"},
        ),
        migrations.AlterModelOptions(
            name='encryptedfile',
            options={'ordering': ['-encrypted_at'], 'verbose_name': 'Fichier chiffré', 'verbose_name_plural': 'Fichiers chiffrés'},
        ),
        migrations.AlterModelOptions(
            name='encryptionkey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clé de chiffrement', 'verbose_name_plural': 'Clés de chiffrement'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=crypto_app.models.avatar_upload_path, verbose_name='Photo de profil'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='crypto_app__user_id_7bf906_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['severity'], name='crypto_app__severit_eccc86_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='crypto_app__action_b87a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['user', '-encrypted_at'], name='crypto_app__user_id_b0c1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['is_encrypted'], name='crypto_app__is_encr_2af4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['user', '-created_at'], name='crypto_app__user_id_8f4ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['user', 'is_active'], name='crypto_app__user_id_0f21eb_idx'),
        ),
    ]
