# Generated by Django 6.0.2 on 2026-03-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0003_userprofile_otp_code_userprofile_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_verified',
        ),
    ]
